Home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

Usuario/urls.py
from django.urls import path
from . import views

app_name = 'Usuario'

urlpatterns = [
    path('cadastro/', views.usuario_cadastro, name='cadastro'),
    path('login/', views.usuario_login, name='login'),
    path('logout/', views.usuario_logout, name='logout'),
]

formularios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('Usuario.urls')),
    path('', include('Home.urls'))
]

Home/models.py
from django.db import models

# Create your models here.

Usuario/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):

    def __str__(self):
        return self.username

Usuario/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms 

from .models import Usuario


class CadastroForm(UserCreationForm):
    password1 = forms.CharField(
        label='Senha',
        strip=False,
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    
    password2 = forms.CharField(
        label='Confirmar Senha',
        strip=False,
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    
    class Meta:
        model = Usuario
        fields = ['username']
        labels = {
            'username': 'Usuário'
        }
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
            })
        }
        
        
class LoginForm(forms.Form):
    username = forms.CharField(
        label = 'Usuário',
        max_length=150,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        label = 'Senha',
        strip=False,
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    

Home/views.py
from django.shortcuts import render
from Utils.decorator import login_required

@login_required
def home(request):
    
    context = {
        'usuario': request.user,
        'status': request.GET.get('status')
    }
    
    return render(request, 'home.html', context)

Usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .forms import CadastroForm, LoginForm

# Create your views here.
def usuario_cadastro(request):
    form = CadastroForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('Usuario:login')
    
    return render(request, 'cadastro.html', {'form': form})


def usuario_login(request):
    
    form = LoginForm(request.POST or None)
 
    context = {
        'form': form,
        'errorCredentials': False,
        'status': request.GET.get('status')
    }
    
    if form.is_valid():
        user = authenticate(
            request,
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        if user is not None:
            login(request, user)
            return redirect('home:home')
        
        context['errorCredentials'] = True
        
    return render(request, 'login.html', context)
        
        
def usuario_logout(request):
    logout(request)
    return redirect('Usuario:login')

Home/templates/home.html
<div>
    <center>
        <h1>HOME AQUI</h1>
    </center>
    
</div>

Usuario/templates/cadastro.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md">
        <br>
        <nav>
            <h1>Cadastre-se</h1>
        </nav>
        <hr>
        <form method="POST" action="">
            {% csrf_token %} {{ form.username.errors }}
            <label>Digite o usuário:</label> {{ form.username }}
            <br> {{ form.password1.errors }}
            <label>Digite a senha:</label> {{ form.password1 }}
            <br> {{ form.password2.errors }}
            <label>Confirme a senha: </label> {{ form.password2 }}
            <br>
            <input class="btn btn-success btn-lg" type="submit"><br>
            <a href="{% url 'Usuario:login' %}" class="btn btn-info btn-lg">Logar</a>
        </form>
    </div>
    <div class="col-md-3">
    </div>
</div>
{% endblock content %}

Usuario/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md">
        <br>
        <h1>Login</h1>
        <hr>

        {% if status == '403' %}
            <p>Você precisa estar logado.</p>
        {% endif %}

        {% if errorCredentials %}
            <p>Credenciais inválidas.</p>
        {% endif %}

        <form method="POST" action="">
            {% csrf_token %}
            {{ form.username.errors }}
            <label>Digite o usuário:</label>
            {{ form.username }}
            <br>
            {{ form.password.errors }}
            <label>Digite a senha:</label>
            {{ form.password }}
            <br>
            <input class="btn btn-success btn-lg" type="submit">
            <a href="{% url 'Usuario:cadastro' %}" class="btn btn-info btn-lg">Cadastre-se</a>
        </form>

    </div>
    <div class="col-md-3">

    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="pt-br">
  <title>{% block title %}{% endblock title%}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>